import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
  scryptSync,
  timingSafeEqual,
  createHash,
} from 'node:crypto';
import { getDb, transaction } from '../client';
import { recordAudit } from './audit';
import { generateSecret, generateRecoveryCodes, normaliseRecoveryCode } from '@/lib/auth/totp';
import type { ExecutiveRole } from '@/lib/types/finance';

/**
 * MFA enrolment state.
 *
 * SECRET STORAGE
 *
 * TOTP secrets are symmetric: whoever holds one can generate valid codes
 * forever. Storing them in plaintext would mean a leaked database — or a
 * backup snapshot, which this application now ships off-box on a schedule —
 * hands an attacker a working second factor for every enrolled user, silently.
 *
 * Encrypted with AES-256-GCM under a key derived from AUTH_SECRET. That ties
 * the secrets to a value already required to be present and protected, and
 * GCM's tag means a tampered ciphertext fails loudly rather than decrypting to
 * garbage that produces wrong codes nobody can explain.
 *
 * The honest limit: AUTH_SECRET lives in the same environment as the database,
 * so this protects against a leaked *snapshot*, not against a compromised
 * host. A KMS-held key is the next step and is a deployment change rather than
 * a code one.
 */

function encryptionKey(): Buffer {
  const secret = process.env.AUTH_SECRET;
  if (!secret || secret.length < 16) {
    throw new Error('AUTH_SECRET must be set to store MFA secrets.');
  }
  // Fixed salt: the key must be derivable across restarts and processes, and
  // AUTH_SECRET is already the high-entropy input. A random salt would have to
  // be stored beside the ciphertext, which buys nothing here.
  return scryptSync(secret, 'capexiq-mfa-v1', 32);
}

function encryptSecret(plaintext: string): string {
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', encryptionKey(), iv);
  const enc = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  return `v1.${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${enc.toString('base64')}`;
}

function decryptSecret(stored: string): string {
  const [version, ivB64, tagB64, dataB64] = stored.split('.');
  if (version !== 'v1') throw new Error('Unrecognised MFA secret encoding.');

  const decipher = createDecipheriv(
    'aes-256-gcm',
    encryptionKey(),
    Buffer.from(ivB64, 'base64')
  );
  decipher.setAuthTag(Buffer.from(tagB64, 'base64'));
  return Buffer.concat([
    decipher.update(Buffer.from(dataB64, 'base64')),
    decipher.final(),
  ]).toString('utf8');
}

/**
 * Recovery codes are hashed with SHA-256, not PBKDF2.
 *
 * They are 40 bits of uniform randomness generated by the server, not a
 * human-chosen password, so there is no dictionary to run and stretching buys
 * nothing against brute force that the entropy does not already provide. The
 * relevant property is that a database reader cannot use them, which a plain
 * hash gives.
 */
function hashRecoveryCode(code: string): string {
  return createHash('sha256').update(normaliseRecoveryCode(code)).digest('hex');
}

export interface MfaState {
  userId: string;
  confirmed: boolean;
  createdAt: string;
  confirmedAt: string | null;
  lastUsedCounter: number | null;
  unusedRecoveryCodes: number;
}

interface MfaRow {
  user_id: string;
  secret_encrypted: string;
  created_at: string;
  confirmed_at: string | null;
  last_used_counter: number | null;
  disabled_at: string | null;
}

function row(userId: string): MfaRow | undefined {
  return getDb()
    .prepare('SELECT * FROM user_mfa WHERE user_id = ? AND disabled_at IS NULL')
    .get(userId) as MfaRow | undefined;
}

/** Is MFA active for this user? Only a confirmed enrolment counts. */
export function isMfaEnabled(userId: string): boolean {
  const found = row(userId);
  return Boolean(found?.confirmed_at);
}

export function getMfaState(userId: string): MfaState | null {
  const found = row(userId);
  if (!found) return null;

  const unused = getDb()
    .prepare('SELECT COUNT(*) AS n FROM mfa_recovery_codes WHERE user_id = ? AND used_at IS NULL')
    .get(userId) as { n: number };

  return {
    userId,
    confirmed: Boolean(found.confirmed_at),
    createdAt: found.created_at,
    confirmedAt: found.confirmed_at,
    lastUsedCounter: found.last_used_counter,
    unusedRecoveryCodes: unused.n,
  };
}

/** The decrypted secret, for verification only. Never returned to a client. */
export function getSecret(userId: string): string | null {
  const found = row(userId);
  return found ? decryptSecret(found.secret_encrypted) : null;
}

/**
 * Begin enrolment.
 *
 * Replaces any unconfirmed enrolment so a user who abandoned a previous
 * attempt is not stuck with a secret their phone never received. A *confirmed*
 * enrolment is never silently replaced — that would be a way to reset someone
 * else's second factor.
 */
export function beginEnrolment(userId: string): { secret: string } {
  const existing = row(userId);
  if (existing?.confirmed_at) {
    throw new Error('MFA is already enabled for this account.');
  }

  const secret = generateSecret();
  const now = new Date().toISOString();

  getDb()
    .prepare(
      `INSERT INTO user_mfa (user_id, secret_encrypted, created_at)
       VALUES (?, ?, ?)
       ON CONFLICT (user_id) DO UPDATE SET
         secret_encrypted = excluded.secret_encrypted,
         created_at       = excluded.created_at,
         confirmed_at     = NULL,
         last_used_counter = NULL,
         disabled_at      = NULL`
    )
    .run(userId, encryptSecret(secret), now);

  return { secret };
}

/**
 * Confirm enrolment and issue recovery codes.
 *
 * The codes are returned exactly once, in this response. Storing them
 * retrievably would make them a second copy of the factor sitting in the same
 * database as the first.
 */
export function confirmEnrolment(
  userId: string,
  role: ExecutiveRole,
  counter: number
): { recoveryCodes: string[] } {
  return transaction((db) => {
    const now = new Date().toISOString();

    db.prepare(
      'UPDATE user_mfa SET confirmed_at = ?, last_used_counter = ? WHERE user_id = ?'
    ).run(now, counter, userId);

    // A re-enrolment must not leave the previous set usable.
    db.prepare('DELETE FROM mfa_recovery_codes WHERE user_id = ?').run(userId);

    const codes = generateRecoveryCodes();
    const insert = db.prepare(
      'INSERT INTO mfa_recovery_codes (user_id, code_hash, created_at) VALUES (?, ?, ?)'
    );
    for (const code of codes) insert.run(userId, hashRecoveryCode(code), now);

    recordAudit({
      actorUserId: userId,
      actorRole: role,
      action: 'auth.login',
      entity: 'mfa',
      entityId: userId,
      summary: 'Multi-factor authentication enabled',
    });

    return { recoveryCodes: codes };
  });
}

/** Record the counter a successful code came from, so it cannot be replayed. */
export function recordCounter(userId: string, counter: number): void {
  getDb()
    .prepare('UPDATE user_mfa SET last_used_counter = ? WHERE user_id = ?')
    .run(counter, userId);
}

/**
 * Spend a recovery code.
 *
 * Single use, compared in constant time. Returns how many remain so the caller
 * can warn a user who is running out before they are locked out.
 */
export function consumeRecoveryCode(
  userId: string,
  submitted: string
): { ok: boolean; remaining: number } {
  const target = hashRecoveryCode(submitted);

  const rows = getDb()
    .prepare('SELECT id, code_hash FROM mfa_recovery_codes WHERE user_id = ? AND used_at IS NULL')
    .all(userId) as unknown as Array<{ id: number; code_hash: string }>;

  let matched: number | null = null;
  for (const candidate of rows) {
    const a = Buffer.from(candidate.code_hash, 'hex');
    const b = Buffer.from(target, 'hex');
    if (a.length === b.length && timingSafeEqual(a, b)) matched = candidate.id;
  }

  if (matched === null) return { ok: false, remaining: rows.length };

  getDb()
    .prepare('UPDATE mfa_recovery_codes SET used_at = ? WHERE id = ?')
    .run(new Date().toISOString(), matched);

  return { ok: true, remaining: rows.length - 1 };
}

/**
 * Turn MFA off.
 *
 * Soft-disabled and audited rather than deleted: "when did this account stop
 * requiring a second factor, and who did it" is exactly the question an
 * incident review asks, and a deleted row cannot answer it.
 */
export function disableMfa(userId: string, role: ExecutiveRole): void {
  transaction((db) => {
    db.prepare('UPDATE user_mfa SET disabled_at = ? WHERE user_id = ?').run(
      new Date().toISOString(),
      userId
    );
    db.prepare('DELETE FROM mfa_recovery_codes WHERE user_id = ?').run(userId);

    recordAudit({
      actorUserId: userId,
      actorRole: role,
      action: 'auth.logout',
      entity: 'mfa',
      entityId: userId,
      summary: 'Multi-factor authentication disabled',
    });
  });
}

export const __testing = { encryptSecret, decryptSecret, hashRecoveryCode };
