import { NextResponse } from 'next/server';
import OpenAI from 'openai';

export interface BoardMemberStatement {
  role: 'CFO' | 'COO' | 'CRO' | 'Strategy';
  title: string;
  name: string;
  avatar: string;
  verdict: 'APPROVE' | 'CONDITIONAL' | 'DEFER' | 'REJECT';
  statement: string;
  keyConcernOrDriver: string;
}

export interface BoardDebateResponse {
  consensusDecision: 'APPROVE WITH GATES' | 'UNCONDITIONAL APPROVAL' | 'DEFER INVESTIGATION' | 'REJECT';
  consensusSummary: string;
  voteCount: {
    approve: number;
    conditional: number;
    defer: number;
    reject: number;
  };
  statements: BoardMemberStatement[];
  stageGates: string[];
  disclaimer: string;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { assumptions, metrics, selectedScenario } = body;

    const npv = metrics?.npv ? `AED ${(metrics.npv / 1000000).toFixed(2)}M` : 'AED 12.08M';
    const irr = metrics?.irr ? `${(metrics.irr * 100).toFixed(1)}%` : '26.3%';
    const mirr = metrics?.mirr ? `${(metrics.mirr * 100).toFixed(1)}%` : '19.3%';
    const payback = metrics?.paybackPeriodYears ? `${metrics.paybackPeriodYears.toFixed(1)} years` : '3.1 years';
    const wacc = assumptions?.discountRate ? `${(assumptions.discountRate * 100).toFixed(1)}%` : '11.5%';

    const fallbackResponse: BoardDebateResponse = {
      consensusDecision: 'APPROVE WITH GATES',
      consensusSummary: `The Executive Board debate concluded with a unified consensus to APPROVE WITH GATES for the AED 24.0M NovaRetail GCC Dubai Micro-Fulfilment Centre proposal. Strong financial metrics (NPV of ${npv}, IRR of ${irr} vs ${wacc} WACC) satisfy capital hurdle requirements, while operationally compressing delivery SLAs from 24h to 2h. However, capital release is gated across 3 deployment phases to mitigate robotics integration and utility cost risks.`,
      voteCount: {
        approve: 2,
        conditional: 2,
        defer: 0,
        reject: 0,
      },
      statements: [
        {
          role: 'CFO',
          title: 'Chief Financial Officer',
          name: 'Tariq Al-Mansoor',
          avatar: '👔',
          verdict: 'APPROVE',
          statement: `From a capital allocation standpoint, an NPV of ${npv} and an IRR of ${irr} substantially clear our corporate hurdle rate of ${wacc}. Modified IRR (${mirr}) remains robust under realistic reinvestment assumptions. Capital outlay is fully recovered in ${payback}. I vote to approve.`,
          keyConcernOrDriver: 'High Profitability Index (1.50x) and strong debt service coverage.',
        },
        {
          role: 'COO',
          title: 'Chief Operating Officer',
          name: 'Sarah Jenkins',
          avatar: '⚙️',
          verdict: 'CONDITIONAL',
          statement: `Operating SLA compression from 24 hours down to 2 hours with 8,000 orders/day throughput transforms our UAE market position. However, I condition my approval on vendor WCS/WMS milestone sign-offs to avoid warehouse integration delays.`,
          keyConcernOrDriver: '71% fulfillment cost reduction per order (AED 14.50 to AED 4.20).',
        },
        {
          role: 'CRO',
          title: 'Chief Risk Officer',
          name: 'Dr. Faisal Al-Hassan',
          avatar: '⚖️',
          verdict: 'CONDITIONAL',
          statement: `While 9% UAE corporate tax leaves OCF strong, our sensitivity analysis shows vulnerability to electricity tariff hikes and supply chain inflation. I require a 15% CapEx overrun cap in vendor contracts before signing.`,
          keyConcernOrDriver: 'DEWA utility tariff escalation and Monte Carlo downside risk in Year 2.',
        },
        {
          role: 'Strategy',
          title: 'Strategy & Governance Director',
          name: 'Elena Rostova',
          avatar: '🎯',
          verdict: 'APPROVE',
          statement: `This investment establishes a high-defensibility urban fulfillment barrier against regional e-commerce competitors. The 5-stage Real Options framework allows us to expand into Abu Dhabi once Dubai MFC reaches 70% capacity.`,
          keyConcernOrDriver: 'Urban darkstore network scalability and market share expansion.',
        },
      ],
      stageGates: [
        'Gate 1 (AED 14.0M): Site lease finalization, MEP preparation, and primary AMR robotics procurement.',
        'Gate 2 (AED 8.0M): WMS software integration, pilot testing, and staff operations onboarding.',
        'Gate 3 (AED 2.0M): Final working capital release upon achieving 4,000 orders/day SLA throughput.',
      ],
      disclaimer: 'This C-Suite Board Debate transcript is generated by CapExIQ AI for decision-support synthesis. Financial math remains 100% deterministic.',
    };

    const apiKey = process.env.OPENAI_API_KEY;
    const model = process.env.OPENAI_MODEL || 'gpt-4o';

    if (!apiKey) {
      return NextResponse.json(fallbackResponse);
    }

    const openai = new OpenAI({ apiKey });

    const systemPrompt = `You are an Autonomous C-Suite Executive Board Simulator for NovaRetail GCC evaluating a AED 24.0M Micro-Fulfilment Centre investment proposal.
Simulate a debate between 4 board members:
1. CFO (Tariq Al-Mansoor): Financial metrics, NPV, IRR, WACC, capital discipline.
2. COO (Sarah Jenkins): Fulfillment SLA (24h to 2h), throughput, warehouse automation.
3. CRO (Dr. Faisal Al-Hassan): Inflation, DEWA electricity tariffs, risk mitigation, contracts.
4. Strategy Director (Elena Rostova): Competitive moat, expansion options, market growth.

Return ONLY a JSON object matching this schema:
{
  "consensusDecision": "APPROVE WITH GATES" | "UNCONDITIONAL APPROVAL" | "DEFER INVESTIGATION" | "REJECT",
  "consensusSummary": string,
  "voteCount": { "approve": number, "conditional": number, "defer": number, "reject": number },
  "statements": [
    {
      "role": "CFO" | "COO" | "CRO" | "Strategy",
      "title": string,
      "name": string,
      "avatar": string,
      "verdict": "APPROVE" | "CONDITIONAL" | "DEFER" | "REJECT",
      "statement": string,
      "keyConcernOrDriver": string
    }
  ],
  "stageGates": string[],
  "disclaimer": string
}`;

    const userPrompt = `Financial Model Context:
- Scenario: ${selectedScenario || 'Base'}
- Initial Capital Outlay: AED ${metrics?.totalInitialOutlay ? (metrics.totalInitialOutlay / 1000000).toFixed(2) + 'M' : '24.0M'}
- NPV: ${npv}
- IRR: ${irr}
- MIRR: ${mirr}
- WACC Hurdle Rate: ${wacc}
- Payback Period: ${payback}

Simulate the executive board debate and output structured JSON.`;

    const completion = await openai.chat.completions.create({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.3,
    });

    const content = completion.choices[0]?.message?.content;
    if (content) {
      const parsed = JSON.parse(content) as BoardDebateResponse;
      return NextResponse.json(parsed);
    }

    return NextResponse.json(fallbackResponse);
  } catch (error: any) {
    console.error('Error in /api/ai/board-debate:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to simulate board debate' },
      { status: 500 }
    );
  }
}
