import { NextResponse } from 'next/server';
import OpenAI from 'openai';
import crypto from 'crypto';

export interface BoardMemoResponse {
  memoTitle: string;
  documentRef: string;
  date: string;
  auditHash: string;
  targetEntity: string;
  executiveSummary: string;
  financialJustification: string;
  keyDrivers: string[];
  principalRisks: string[];
  recommendedDecision: string;
  signoffBlocks: Array<{
    role: string;
    title: string;
    name: string;
    status: 'APPROVED' | 'PENDING';
  }>;
  disclaimer: string;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { assumptions, metrics, selectedScenario } = body;

    // Generate SHA-256 audit hash derived from model state
    const modelPayload = JSON.stringify({
      assumptions,
      npv: metrics?.npv,
      irr: metrics?.irr,
      scenario: selectedScenario,
    });
    const auditHash = crypto.createHash('sha256').update(modelPayload).digest('hex');

    const npv = metrics?.npv ? `AED ${(metrics.npv / 1000000).toFixed(2)}M` : 'AED 12.08M';
    const irr = metrics?.irr ? `${(metrics.irr * 100).toFixed(1)}%` : '26.3%';
    const mirr = metrics?.mirr ? `${(metrics.mirr * 100).toFixed(1)}%` : '19.3%';
    const payback = metrics?.paybackPeriodYears ? `${metrics.paybackPeriodYears.toFixed(1)} years` : '3.1 years';
    const wacc = assumptions?.discountRate ? `${(assumptions.discountRate * 100).toFixed(1)}%` : '11.5%';

    const fallbackMemo: BoardMemoResponse = {
      memoTitle: 'Formal Capital Expenditure Board Investment Memorandum',
      documentRef: `MEMO-NOVA-2026-${auditHash.substring(0, 8).toUpperCase()}`,
      date: new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
      auditHash: auditHash,
      targetEntity: 'NovaRetail GCC (Dubai South Micro-Fulfilment Hub)',
      executiveSummary: `This Board Investment Memorandum formally requests approval for an AED 24.00,000 capital outlay (AED 22.0M CapEx + AED 2.0M Working Capital) for constructing an Automated Micro-Fulfilment Centre in Dubai. The project establishes an urban automated distribution hub compressing order delivery SLAs from 24 hours down to 2 hours while reducing direct order fulfillment cost by 71%.`,
      financialJustification: `The proposal cleared all investment hurdle criteria under deterministic baseline valuation: Net Present Value (NPV) stands at ${npv} discounted at ${wacc} WACC, delivering an Internal Rate of Return (IRR) of ${irr} (MIRR: ${mirr}). Initial capital is fully recovered within ${payback} on a discounted payback basis.`,
      keyDrivers: [
        'Annual process & manual labor cost savings of AED 7.50M (71% savings per order).',
        'Incremental 2-hour delivery SLA margin conversion yielding AED 2.50M in Year 1.',
        'High capital efficiency with Profitability Index of 1.50x (generating AED 1.50 PV per AED 1.00 outlay).',
        'Favorable tax regime: 9% UAE corporate tax leaves Year-1 Operating Cash Flow robust at AED 7.4M.',
      ],
      principalRisks: [
        'Robotics & WMS software commissioning delay risking Year-1 volume ramp-up.',
        'DEWA commercial electricity slab tariff escalation exceeding projected 3.0% inflation.',
        'Downside sensitivity under pessimistic scenario where benefit realization drops by 25%.',
      ],
      recommendedDecision: 'APPROVE WITH STAGE-GATE CAPITAL RELEASE',
      signoffBlocks: [
        { role: 'CFO', title: 'Chief Financial Officer', name: 'Tariq Al-Mansoor', status: 'APPROVED' },
        { role: 'CEO', title: 'Chief Executive Officer', name: 'Rashid Al-Maktoum', status: 'APPROVED' },
        { role: 'COO', title: 'Chief Operating Officer', name: 'Sarah Jenkins', status: 'APPROVED' },
      ],
      disclaimer: 'This memorandum was generated by CapExIQ AI using 100% deterministic financial outputs. SHA-256 hash guarantees data integrity for audit compliance.',
    };

    const apiKey = process.env.OPENAI_API_KEY;
    const model = process.env.OPENAI_MODEL || 'gpt-4o';

    if (!apiKey) {
      return NextResponse.json(fallbackMemo);
    }

    const openai = new OpenAI({ apiKey });

    const systemPrompt = `You are a Senior Corporate Governance Counsel and CFO Adviser for NovaRetail GCC.
Generate a formal C-Level Executive Board Investment Memo in JSON format.

Return ONLY a JSON object matching this schema:
{
  "memoTitle": string,
  "documentRef": string,
  "date": string,
  "auditHash": string,
  "targetEntity": string,
  "executiveSummary": string,
  "financialJustification": string,
  "keyDrivers": string[],
  "principalRisks": string[],
  "recommendedDecision": string,
  "signoffBlocks": [
    { "role": string, "title": string, "name": string, "status": "APPROVED" | "PENDING" }
  ],
  "disclaimer": string
}`;

    const completion = await openai.chat.completions.create({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Financial Context:\n- NPV: ${npv}\n- IRR: ${irr}\n- MIRR: ${mirr}\n- WACC: ${wacc}\n- Payback: ${payback}\n- Scenario: ${selectedScenario}` },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.2,
    });

    const content = completion.choices[0]?.message?.content;
    if (content) {
      const parsed = JSON.parse(content) as BoardMemoResponse;
      parsed.auditHash = auditHash; // Ensure exact cryptographic hash
      return NextResponse.json(parsed);
    }

    return NextResponse.json(fallbackMemo);
  } catch (error: any) {
    console.error('Error in /api/ai/board-memo:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate board memo' },
      { status: 500 }
    );
  }
}
